### ISSUE TITLE
Enable Continuous Integration

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber_doc#1]
We require a PDF artifact per commit compiled on the cloud.

**Comment by buddhi1980** [comment]
Almost done, building works, but I'm still fighting with automatic releasing of PDFs

**Comment by buddhi1980** [comment]
Travis Cl works!  All tagged builds will be added to releases.

**Comment by ghost** [comment]
Thanks buddhi!🔣

**Comment by ghost** [comment]
I will examine appveyor today

**Comment by ghost** [comment]
We have the appveyor stub.
1.) silent install the latex tools
2.) determine build cmd
