### ISSUE TITLE
A few issues in the text

### ISSUE THREAD

**Issue by GithubSuckBigTime** [buddhi1980/mandelbulber_doc#10]
Hello,

I love Mandelbulber and came to read a bit of its documentation. I've found a few issues in the text. I understand it's a work in progress, but in order to improve it, I will leave my notes here:

manual/chapters/fractals.tex#L5:
  "even at very high (up to infinite) magnification."
  There is no infinite magnification, only ad infinitum (https://en.wikipedia.org/wiki/Ad_infinitum)

manual/chapters/fractals.tex#L30:
  "\item\emph{c} is the coordinates"
  should be
  "\item\emph{c} is the coordinate" or "\item\emph{c} are the coordinates"

manual/chapters/fractals.tex#L34:
  "( these points represent the"
  There should be no space after the bracket.

manual/chapters/fractals.tex#L94:
  "fractal type, the ``Mandelbulb''\index{Mandelbulb} is calculated"
  missing comma after "the Mandelbulb"

manual/chapters/distance_estimation.tex#L11:
  "tracking a ``photon'' traveling toward the object"
  The analogy of photons can be confusing because photons usually travel from light towards the eye, not the other way around. This can further suggest the existing photon mapping rendering technique, which is not what is used here. I would rather talk about rays than photons.

manual/chapters/distance_estimation.tex#L30:
  "This distance is less"
  should be 
  "This distance is smaller"

manual/chapters/iteration_loop.tex#L124:
  "Once hybrid fractals has been enabled"
  should be
  "Once hybrid fractals have been enabled"

**Comment by buddhi1980** [comment]
Hi
Thanks for your comments
Do you want to make these changes directly in the repository? I can grant you an access.

**Comment by mclarekin** [comment]
Thanks for this, feed back from the manual is very much appreciated as we
know it still needs a lot of work

If you prefer I will make the changes???

manual/chapters/iteration_loop.tex#L124:
"Once hybrid fractals has been enabled"
should be
"Once Hybrid Mode has been enabled"

**Comment by GithubSuckBigTime** [comment]
I am not actively using this account, I only have it for submitting occasional issues I find here and there :) So I'll leave the incorporation of the changes to someone else. Thank you for your responses and a great job you're doing.

**Comment by mclarekin** [comment]
manual/chapters/fractals.tex#L5:
Reword;  A characteristic feature is that the mathematics often produce
infinite levels of smaller fractal detail, such that viewing the detail is
only limited by the floating point accuracy used in the calculation

manual/chapters/fractals.tex#L30
Reword: is the original position of the image point to be iterated

manual/chapters/fractals.tex#L34
space removed

manual/chapters/fractals.tex#L94
comma inserted

manual/chapters/distance_estimation.tex#L11:
removed photon, and reworded it.

manual/chapters/distance_estimation.tex#L30:
replaced less with smaller

manual/chapters/iteration_loop.tex#L124:
added  word mode  :   hybrid fractals mode

**Comment by zebastian** [comment]
seems done, please reopen, if still open
