### ISSUE TITLE
Background image on title page from facebook challenge

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber_doc#3]
What do you think to replace example image with an image from the facebook community?

**Comment by buddhi1980** [comment]
If we get permission, why not. Do you have some proposal?

**Comment by zebastian** [comment]
what about this:

```
the manual title challenge

Mandelbulber 2.11 is almost finished and will include a great new end user manual explaining most of the features of mandelbulber.
The title page of the manual will include a background image with opacity 0.3.
See current example below.

We are looking for some user work to put there, so thats the challenge:
- the image should fit properly on DINa4 portrait, so image resolution should be 1000x1414 or higher
- you should be willing to put the image under public license
- the challenge ends monday the 24th

The image with the most upvotes wins. 

May the odds be ever in your favour!
```

**Comment by buddhi1980** [comment]
Well writren. Can you post it on fb?

**Comment by zebastian** [comment]
I have posted on FB

**Comment by ghost** [comment]
Please rename the Facebook group to "mandelbulber". We do not require (not mandelbulb3d). In my opinion, we should invite and include all fractals including Mandelbulb 3d images. 

Any thoughts?

**Comment by buddhi1980** [comment]
I don't agree. The same rule is on similar group for Mandelbulb3d. The name of the group is very good, because many people think that Mandelbulber and Mandelbulb3d is the same program

**Comment by ghost** [comment]
(Not mandelbulb3d) carries a negative connotation. Please consider my request to update the group name. It feels like exclusion and we do not need that.

**Comment by ghost** [comment]
Btw, bavk to th topic; I really like the contest. Very smart idea! We want to expand our outreach and involve the user base as much as possible. I want to absorb the mandelbulb3d community 😄🚒

**Comment by zebastian** [comment]
Assimilate, undermine and destroy :D

About the title: IMHO the suffix "(Not mandelbulb3d)" is fine, people get confused by the program names.

**Comment by ghost** [comment]
We want to be the undisputed champion of fractal software. We do this by rewriting and absorbing all the competition and utilizing the high value differences. 

Interestingly, when I talk to other colleagues about 3d fractals, they know the Mandelbulb. The use of 3d and -er seems so insignificant. I am working diligently to convert the entire mandelbulber3d codebase from pascal into c. However its still riddled with ASM.

**Comment by ghost** [comment]
@zebastian finally recompiled and investigated the topic. very impressive!
**
![image](https://cloud.githubusercontent.com/assets/7040493/25346992/74f2edd4-28e7-11e7-9247-2dd0d42bca8f.png)
**

**Comment by ghost** [comment]
looks great with new image
